apiVersion: v1
kind: Service
metadata:
  name: node-todoapp-server-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31001
  selector:
    app: node-todoapp-server
  type: LoadBalancer
